server:
  port: 5001
  error:
    include-message: always    include-binding-errors: always
spring:
  application:
    name: SeamosAmigos
  datasource:
    url: jdbc:mysql://localhost:3306/seamos_amigos_db
    username: admin
    password: admin
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
logging:
  file:
    name: ./app-log/seamos-amigos.log   
